<?php

/**
 * Implements hook_cron()
 */

function friend_email_cron() {
   
    $result = db_query("SELECT friend_bdate_value, entity_id
            FROM field_data_friend_bdate 
            LEFT JOIN field_data_friend_email ON field_data_friend_bdate.entity_id = field_data_friend_email.entity_id;
            WHERE friend_bdate_value = DATE(NOW())");
    

    foreach ($result as $bdays) {
        $module = 'friend_email';
        $key = '';
        $from = 'admin@localhost.com';
        $to_user_mail = $bdays['field_data_friend_email'];
        $message = drupal_mail($module, $key, $to_user_mail, LANGUAGE_NONE, array(), $from, FALSE);
        $message['subject'] = 'Happy Birthday';
        $message['body'] = array();
        $message['body'][] = 'Happy Birthday to You!!!';

        $system = drupal_mail_system($module, $key);
        $message = $system->format($message);
        $message['result'] = $system->mail($message);
    }
}